### ISSUE TITLE
documentation uploaded incorrect

### ISSUE THREAD

**Issue by stonier** [utexas-bwi/concert_scheduling#10]
The documentation link you have in the readme is probably going to the correct url:

http://farnsworth.csres.utexas.edu/docs/concert_simple_scheduler/html/

but looks as though you've accidentally uploaded the rocon_request_scheduler docs there.

**Comment by jack-oquin** [comment]
I tried to fix this at UT today, but my workspace here is so screwed up I can't even build the docs right now.

I'll fix it tonight when I get home.

**Comment by stonier** [comment]
Not urgent. I can follow the inlune documentation. Ths was just a notification.

**Comment by jack-oquin** [comment]
OK, the correct docs are there now.

But, there is no node-level usage documentation yet. I'll add that as a README and link it into the docs.

**Comment by jack-oquin** [comment]
Added README.rst describing the node interface: 
- https://github.com/utexas-bwi/rocon_experimental/blob/master/concert_simple_scheduler/README.rst
- http://farnsworth.csres.utexas.edu/docs/concert_simple_scheduler/html/README.html 

Closing this issue for now, but please provide comments and feedback and re-open if desired.
