### ISSUE TITLE
Invalid request string constant

### ISSUE THREAD

**Issue by stonier** [utexas-bwi/concert_scheduling#12]
In https://github.com/utexas-bwi/rocon_experimental/blob/master/concert_simple_scheduler/src/concert_simple_scheduler/scheduler_node.py#L197

```
if hasattr(Request, "INVALID"):  # new reason code defined?      
    element.request.cancel(Request.INVALID)
```

Planning or have already implemented this?

**Comment by jack-oquin** [comment]
I don't think I ever added that reason code.

Please add it, if you agree that it's a good idea.

**Comment by stonier** [comment]
Added in https://github.com/robotics-in-concert/rocon_msgs/commit/f23bc8885eb41cc0fe866dc4db01329fa11510e6
