### ISSUE TITLE
Start app on allocated resources

### ISSUE THREAD

**Issue by stonier** [utexas-bwi/concert_scheduling#13]
Do you plan to start apps upon granting resources?

We talked about this fleetingly earlier. Probably `no. of schedulers < no. of requesters` so it would be good to centralise the start app code in the few schedulers we have.

I can hack on this and send you a PR if you like.

**Comment by jack-oquin** [comment]
When we discussed doing that before, it seemed reasonable. I hadn't thought about it since.

A PR would be very welcome. I am sure you have a much better idea what it needs to do. 

If it can mostly be encapsulated into another Python module, that might make it easier for other schedulers to reuse.

**Comment by stonier** [comment]
Will do once a couple of other bugs are sorted.

**Comment by stonier** [comment]
Thinking of creating a class in the conductor for this - RappHandler. It can be initalised with information from the `concert_client_changes` msg, and thereafter easily used to start/stop apps with exceptions when things go wrong.

Would this work?

Another alternative is to generalise the PoolResource class for any scheduler to work with. It would initialise from a `concert_client_changes` msg and updates with any new information from the same topic.

**Comment by stonier** [comment]
A rapp handler in concert_conductor: https://github.com/robotics-in-concert/rocon_concert/commit/a0f5ba0c05b56f4f97c819ec4db633a117fd309d

Rapp handler additions in the simple scheduler: https://github.com/robotics-in-concert/rocon_experimental/commit/5ab8790f7f3b41ed0f258a3370bcc0ff41c6ca6a

This gets my teleop demo working, but I'll wait for any input you have before pull requesting this. One thing I can think of, this will need a flag to skip start/stop of apps for any unit tests.

**Comment by jack-oquin** [comment]
The `RappHandler` interface looks great. That's just what I was hoping for. 

If the conductor does not use it, perhaps it should reside in some other package to minimize dependencies. So far, the scheduler modules only depend on various message packages and each other. You should decide where best to package it, `rocon_scheduler_requests` might actually be a reasonable option.

I would like `resource_pool` to become general enough for other schedulers to re-use it, perhaps via derived classes. But, my basic unit test design for `resource_pool` and similar low-level modules is to generate and process ROS messages, but avoid sending or receiving them. That way, the internals can be tested directly by nosetests, without needing a rostest environment. 

Right now, most things involving ROS I/O are done directly in the scheduler_node module. That is not the desired goal, just a temporary mode of experimentation. Just as `rocon_scheduler_requests.scheduler` provides ROS I/O for the requests, I would eventually like to wrap the `resource_pool` in a higher-level module that handles the necessary message and service calls. 

For now, I'd prefer to do the `rapp_handler.start()` and `rapp_handler.stop()` in the scheduler_node. I'll move it out of there when I figure out how to provide a better abstraction.

**Comment by stonier** [comment]
Yeah, I also wondered about the location of the `RappHandler`. I don't think anybody else would use this code, so in `rocon_scheduler_requests` sounds like the best fit. I'll make a pull request for that.

Shall I leave you to work out your desired implementation in the scheduler node? I can test it once it's in.

**Comment by jack-oquin** [comment]
Yes, that sounds good.

**Comment by jack-oquin** [comment]
The `PoolResource` changes (robotics-in-concert@5ab8790) are not correct as written, because the `msg` argument to `__init__()` is not always a `concert_msgs/ConcertClient`. 

Since that _is_ the usual message when an actual scheduler creates a `PoolResource` instance, the best solution is to restrict the argument to only that message type. The difficulty is that the unit tests mostly use the other types of messages:  `CurrentStatus` or `Resource`, so that will require significant re-work.

**Comment by stonier** [comment]
I see. Is [duck typing](http://en.wikipedia.org/wiki/Duck_typing) (or even worse, introspecting the type) an option here?

**Comment by jack-oquin** [comment]
Good idea. 

It will probably work, and would ease migration away from those other message types. I'd like to remove them, anyway, but not this week.

**Comment by jack-oquin** [comment]
Everything is now combined into the [utexas-bwi/concert_scheduling](https://github.com/utexas-bwi/concert_scheduling) repository.

I have added the start and stop code to the simple_scheduler. I did it by wrapping the resource_pool classes with a pair of ROS-aware classes in the [scheduler_clients](https://github.com/utexas-bwi/concert_scheduling/blob/master/concert_resource_pool/src/concert_resource_pool/scheduler_clients.py) module of the new [concert_resource_pool](https://github.com/utexas-bwi/concert_scheduling/tree/master/concert_resource_pool) package.  

My unit tests for this new feature are inadequate, but they succeed. However, when I try to run this ROCON test, it fails:

```
rocon_launch turtle_concert turtle.concert --screen scheduler_type:=simple 
```

Still trying to figure out why.

**Comment by jack-oquin** [comment]
I think starting and stopping rapps is working now.

The turtle_concert test still fails, but it looks like #16 is the problem.

**Comment by stonier** [comment]
Verified that it works except for the problem in #16. Tested with the latest from `concert_scheduling` and

```
> rocon_launch turtle_concert turtle.concert --screen scheduler_type:=simple 
```

with a sleep for 10s before requesting turtles, i.e. before the `request_turtles()` loop in:

https://github.com/robotics-in-concert/rocon_tutorials/blob/indigo/concert_tutorials/turtle_concert/scripts/turtle_pond.py#L56

Also works with:

```
> rocon_launch turtle_concert teleop.concert --scheduler_type:=simple --screen
```

and the concert rqt teleop program accessible via `rocon_remocon` in another shell. Should be good to close if you're happy with it Jack.

**Comment by jack-oquin** [comment]
Thanks for running that test, Daniel. 

Your results combined with the new mock gateway unit test are convincing enough. Closing now.
