### ISSUE TITLE
Requester workflow problem

### ISSUE THREAD

**Issue by stonier** [utexas-bwi/concert_scheduling#14]
Seems to be a problem with a particular flow of events in the scheduler:

I have an example in which the following happens.
- A requester immediately sends off a requests to the scheduler.
- The SchedulerRequests callback [_allocate_resources](https://github.com/utexas-bwi/rocon_scheduler_requests/blob/master/src/rocon_scheduler_requests/scheduler.py#L201) catches the request
- Eventually this callback tries to construct a [_RequesterStatus](https://github.com/utexas-bwi/rocon_scheduler_requests/blob/master/src/rocon_scheduler_requests/scheduler.py#L57) object [here](https://github.com/utexas-bwi/rocon_scheduler_requests/blob/master/src/rocon_scheduler_requests/scheduler.py#L209):

```
self.requesters[rqr_id] = _RequesterStatus(self, msg)
```
- mid-construction, it tries to handle the initial message and calls `concert_simple_scheduler`'s [callback](https://github.com/utexas-bwi/rocon_experimental/blob/master/concert_simple_scheduler/src/concert_simple_scheduler/scheduler_node.py#L88).
- This queues the request, adds the resources and calls [dispatch()](https://github.com/utexas-bwi/rocon_experimental/blob/master/concert_simple_scheduler/src/concert_simple_scheduler/scheduler_node.py#L105)
- In dispatch, it calls [self.notify_requesters()](https://github.com/utexas-bwi/rocon_experimental/blob/master/concert_simple_scheduler/src/concert_simple_scheduler/scheduler_node.py#L158)
- notify_requesters in turn calls [rocon_scheduler_requests.Scheduler.notify()](https://github.com/utexas-bwi/rocon_scheduler_requests/blob/master/src/rocon_scheduler_requests/scheduler.py#L220) which has the following very important code:

```
self.requesters[requester_id].send_feedback()
```

which doesn't exist yet because we actually haven't got through the construction of _RequesterStatus yet nor added it to the dictionary.

Not sure where you'd like to tackle a fix for this. If you need instructions for a reproducible example, let me know.

**Comment by jack-oquin** [comment]
Thanks for the report. I'll see what I can figure out.

**Comment by jack-oquin** [comment]
Cancelling the out-of-date requests and invoking the callback needs to happen after the `_RequesterStatus` constructor returns. So, `_allocate_resources()` will invoke a new `contact()` method for the initial message.

The change is pretty small and relatively simple. But, the unit tests missed this bug, so instructions for reproducing it would help. Don't know why I hadn't seen it already.

**Comment by stonier** [comment]
This seems to have done the trick. Still struggling with some other issues though. I'll update you with some reproducible rocon demos in an email.

**Comment by jack-oquin** [comment]
Good. Thanks.
