### ISSUE TITLE
Not processing newly allocatable resources

### ISSUE THREAD

**Issue by stonier** [utexas-bwi/concert_scheduling#16]
If a new resource is discovered on `concert_client_changes`, it doesn't proceed to allocate that resource and finally grant a request that is waiting.

I'm digging around for more information now and will update back here.

**Comment by jack-oquin** [comment]
I think I just forgot to implement that part.

**Comment by jack-oquin** [comment]
This is now stopping the turtle_concert test from working.

**Comment by jack-oquin** [comment]
@stonier: with the 2ff7a43 work-around your turtle concert test works for me: 

```
rocon_launch turtle_concert turtle.concert --screen scheduler_type:=simple
```

That is not a proper fix, it just comments out moving requests to the blocked queue. 

I'll leave this issue open until **reschedule()** can move elements to and from the blocked queue.

**Comment by stonier** [comment]
ok.

**Comment by jack-oquin** [comment]
I think this is fixed now by 4990830, but the test coverage is not great.

I managed to trigger the desired conditions by hand. 

It works with the turtle.concert test, but my current turtle_concert version does not seem to trigger those conditions right now, so that does not prove much.

**Comment by stonier** [comment]
Ooops, just noticed that 10s sleep I put in `turtle_concert/scripts/turtle_pond.py` made it to github. I just removed it in https://github.com/robotics-in-concert/rocon_tutorials/commit/e1078aa0475e68af6d931486b50f3dc7027a90e0 and are probably seeing the conditions you were missing:

```
[INFO] [WallTime: 1397665102.214527] Request queued: 42d7215e-1108-4ebf-898d-8347a04cf58d
[INFO] [WallTime: 1397665102.214921] Request queued: 66bb7bf5-f2b3-4e5f-a453-f0ab2df0b9bf
[INFO] [WallTime: 1397665102.511510] reschedule ready queue: 
 id: e57b5cb9-2dd4-47d1-bed1-a77bf20c6269
  seq: 0
  request: id: 42d7215e-1108-4ebf-898d-8347a04cf58d
    priority: 0
    resources: 
      rocon:/#turtle_concert/turtle_stroll
    status: 2
 id: e57b5cb9-2dd4-47d1-bed1-a77bf20c6269
  seq: 1
  request: id: 66bb7bf5-f2b3-4e5f-a453-f0ab2df0b9bf
    priority: 0
    resources: 
      rocon:/#turtle_concert/turtle_stroll
    status: 2
[INFO] [WallTime: 1397665102.512002] Request blocked: 42d7215e-1108-4ebf-898d-8347a04cf58d
[INFO] [WallTime: 1397665102.512359] Request blocked: 66bb7bf5-f2b3-4e5f-a453-f0ab2df0b9bf
[INFO] [WallTime: 1397665103.890025] Conductor: retrieving client information [guimul]
...
[INFO] [WallTime: 1397665104.226288] Conductor : new client found [guimul]
[INFO] [WallTime: 1397665104.231330] Conductor: retrieving client information [kobuki]
...
[INFO] [WallTime: 1397665104.562343] Conductor : new client found [kobuki]
[INFO] [WallTime: 1397665104.578751] Conductor : invited [kobuki][kobuki12f7421206364dc8b9ebd2724ce6804b]
[INFO] [WallTime: 1397665104.595358] Conductor : invited [guimul][guimul82967bada15746a2946f59302e89f519]
...
[INFO] [WallTime: 1397665107.950989] Conductor : new clients are ready for action ['kobuki', 'guimul']
[INFO] [WallTime: 1397665108.511614] request 42d7215e-1108-4ebf-898d-8347a04cf58d no longer blocked
[INFO] [WallTime: 1397665108.512093] request 66bb7bf5-f2b3-4e5f-a453-f0ab2df0b9bf no longer blocked
[INFO] [WallTime: 1397665109.393186] Request granted: 42d7215e-1108-4ebf-898d-8347a04cf58d
...
[INFO] [WallTime: 1397665110.282509] Request granted: 66bb7bf5-f2b3-4e5f-a453-f0ab2df0b9bf
```

All looks good! :neckbeard:

**Comment by jack-oquin** [comment]
Thanks!

I updated rocon_tutorials and ran it again. That did trigger the appropriate condition, just as above.

Closing now.
