### ISSUE TITLE
deb release for indigo

### ISSUE THREAD

**Issue by stonier** [utexas-bwi/concert_scheduling#30]
@jack-oquin Any chance you could do a deb release for this? I could also do this for you along with our other rocon releases too if you like (lets you just worry about the sources).

**Comment by jack-oquin** [comment]
I'll do it today.

I will also give you pull access to this repo and the corresponding release repo, so you can do release it yourself any time there is urgent need on your side of the international date line.

**Comment by stonier** [comment]
:+1:

**Comment by jack-oquin** [comment]
Built now and in ros-shadow-fixed
