### ISSUE TITLE
scheduler_node: use new ROCON URI matching logic

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/concert_scheduling#9]
The current implementation still uses the Python `re` package to match requests to resources.

**Comment by jack-oquin** [comment]
Documentation: http://docs.ros.org/api/rocon_uri/html/

**Comment by jack-oquin** [comment]
@stonier: Has support for the dotted platform names been dropped?

**Comment by jack-oquin** [comment]
The `rocon_uri` interface is excellent, and well-documented. Commit 0ffca56 is very simple-minded, but straightforward. The actual change is only about two lines. Most of the rest removes the old dotted platform names. I did that as a first step, just to verify that it works.

A better implementation will parse the client URI once when adding it to the pool, not on every comparison.

Caching the parse of the requested _pattern_ will be trickier, but probably do-able.

**Comment by stonier** [comment]
> @stonier: Has support for the dotted platform names been dropped?

yes, we've moved completely over to the `rocon_uri` format.

**Comment by jack-oquin** [comment]
The basic requirement has been satisfied. Could close.

Leaving it open for now as a reminder to cache the parse objects, at least for each resource in the pool, maybe for each active request, too.

**Comment by jack-oquin** [comment]
Closing now. Please re-open if caching the parse objects becomes a noticeable performance problem.
